name:                haskseg
version:             0.1.0.0
synopsis:            Simple unsupervised segmentation model
description:         >
  Implementation of the non-parametric segmentation model
  described in "Type-based MCMC" (Liang, Jordan, and Klein, 2010)
  and "A Bayesian framework for word segmentation Exploring the effects
  of context" (Goldwater, Griffiths, and Johnson, 2009).
homepage:            https://github.com/githubuser/haskseg#readme
license:             BSD3
author:              Tom Lippincott
maintainer:          tom@cs.jhu.edu
copyright:           2018 Tom Lippincott
category:            NLP
extra-source-files:
- README.md

default-extensions:
  - Strict
  - StrictData
  - FlexibleContexts
  - RecordWildCards
  - MultiParamTypeClasses
  - FlexibleInstances
  - OverloadedStrings
  - ScopedTypeVariables
  
dependencies:
  - base >= 4.7 && < 5
  - containers >=0.5.10.2
  - optparse-generic >=1.2.2
  - random >=1.1
  - exact-combinatorics >=0.2.0.8
  - monad-loops >=0.4.3
  - logging-effect >=1.3.2
  - mtl >=2.2.2
  - MonadRandom >=0.5.1.1
  - random-shuffle >=0.0.4
  - vector >=0.12.0.1
  - ansi-terminal >=0.8.0.4
  - zlib >=0.6.1
  - bytestring >=0.10.8.1
  - text >=1.2.2
  - array
library:
  source-dirs: src

executables:
  haskseg:
    dependencies:
      - haskseg
    source-dirs:      app
    main:             Main.hs
