name:                haskmorph
version:             0.1.0.0
synopsis:            Simple unsupervised morphological inference via MCMC
description:         Implementation of the non-parametric morphological model
                     described in "Type-based MCMC" (Liang, Jordan, and Klein, 2010).
homepage:            https://github.com/githubuser/haskmorph#readme
license:             BSD3
author:              Tom Lippincott
maintainer:          tom@cs.jhu.edu
copyright:           2018 Tom Lippincott
category:            NLP
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers >=0.5.10.2
  - optparse-generic >=1.2.2
  - random >=1.1
  - exact-combinatorics >=0.2.0.8
  - monad-loops >=0.4.3
  - logging-effect >=1.3.2
  - mtl >=2.2.2
  - MonadRandom >=0.5.1.1
  - random-shuffle >=0.0.4
  - vector >=0.12.0.1
  
executables:
  haskmorph:
    source-dirs:      src
    main:             Main.hs
